/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as AdminAdminRegistrationsRouteImport } from './routes/_admin.admin.registrations'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as WorkspaceEditIdRouteImport } from './routes/_workspace.edit.$id'
import { Route as WorkspaceRunIdRouteImport } from './routes/_workspace.run.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AdminAdminRegistrationsRoute = AdminAdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const WorkspaceEditIdRoute = WorkspaceEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRunIdRoute = WorkspaceRunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/registrations': typeof AdminAdminRegistrationsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/edit/$id': typeof WorkspaceEditIdRoute
  '/run/$id': typeof WorkspaceRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/registrations': typeof AdminAdminRegistrationsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/edit/$id': typeof WorkspaceEditIdRoute
  '/run/$id': typeof WorkspaceRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_admin/admin/registrations': typeof AdminAdminRegistrationsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_workspace/edit/$id': typeof WorkspaceEditIdRoute
  '/_workspace/run/$id': typeof WorkspaceRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/invite'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/registrations'
    | '/admin/users'
    | '/edit/$id'
    | '/run/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/invite'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/registrations'
    | '/admin/users'
    | '/edit/$id'
    | '/run/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_workspace'
    | '/change-password'
    | '/invite'
    | '/login'
    | '/register'
    | '/_admin/admin'
    | '/_workspace/'
    | '/_admin/admin/registrations'
    | '/_admin/admin/users'
    | '/_workspace/edit/$id'
    | '/_workspace/run/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_admin/admin/registrations': {
      id: '/_admin/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminAdminRegistrationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_workspace/edit/$id': {
      id: '/_workspace/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof WorkspaceEditIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/run/$id': {
      id: '/_workspace/run/$id'
      path: '/run/$id'
      fullPath: '/run/$id'
      preLoaderRoute: typeof WorkspaceRunIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminRegistrationsRoute: typeof AdminAdminRegistrationsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminRegistrationsRoute: AdminAdminRegistrationsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceEditIdRoute: typeof WorkspaceEditIdRoute
  WorkspaceRunIdRoute: typeof WorkspaceRunIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceEditIdRoute: WorkspaceEditIdRoute,
  WorkspaceRunIdRoute: WorkspaceRunIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
